name: metabolinks-environment
channels:
  - conda-forge
dependencies:
  - python
  - pytest
  - six
  - requests
  - numpy
  - matplotlib>=2.0
  - pandas>=0.25
  - xlrd
  - xlsxwriter
  - pandas-flavor